version: "3.8"

services:
  csm-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - HF_TOKEN=${HF_TOKEN}
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./cloned_voices:/app/cloned_voices
      - ./voice_references:/app/voice_references  
      - ./voice_profiles:/app/voice_profiles    
    env_file:
      - .env
    environment:
      - HF_TOKEN=${HF_TOKEN}
    command: sleep infinity
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
